In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [8]:
df_avaliacoes = pd.read_csv('avaliacoes.csv')
df_hospedes = pd.read_csv('hospedes.csv')
df_quartos = pd.read_csv('quartos.csv')
df_reservas = pd.read_csv('reservas.csv')

In [9]:
df_avaliacoes.info()

<class 'pandas.DataFrame'>
RangeIndex: 685 entries, 0 to 684
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id_avaliacao          685 non-null    int64
 1   id_reserva            685 non-null    int64
 2   nota_geral            685 non-null    str
 3   nota_limpeza          681 non-null    float64
 4   nota_atendimento      683 non-null    float64
 5   nota_custo_beneficio  685 non-null    str
 6   comentario            632 non-null    str
 7   data_avaliacao        685 non-null    str
dtypes: float64(2), int64(2), str(4)
memory usage: 42.9 KB

In [10]:
df_avaliacoes.describe()

       id_avaliacao   id_reserva  nota_limpeza  nota_atendimento
count    685.000000   685.000000    681.000000        683.000000
mean     343.000000   501.197080      7.511894          7.534553
std      197.886752   288.072122      1.534790          1.542451
min        1.000000     1.000000      5.000000         -1.000000
25%      172.000000   246.000000      6.200000          6.200000
50%      343.000000   506.000000      7.400000          7.600000
75%      514.000000   746.000000      8.800000          8.900000
max      685.000000  1000.000000     15.000000         13.000000

In [11]:
df_avaliacoes.columns

Index(['id_avaliacao', 'id_reserva', 'nota_geral', 'nota_limpeza',
       'nota_atendimento', 'nota_custo_beneficio', 'comentario',
       'data_avaliacao'],
      dtype='str')

In [12]:
df_hospedes.info()

<class 'pandas.DataFrame'>
RangeIndex: 402 entries, 0 to 401
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_hospede       402 non-null    int64
 1   nome             402 non-null    str
 2   email            402 non-null    str
 3   telefone         402 non-null    str
 4   cidade_origem    401 non-null    str
 5   estado           401 non-null    str
 6   data_nascimento  402 non-null    str
 7   genero           401 non-null    str
dtypes: int64(1), str(7)
memory usage: 25.3 KB

In [13]:
df_hospedes.describe()

       id_hospede
count  402.000000
mean   199.875622
std    115.677488
min      1.000000
25%    100.000000
50%    199.500000
75%    299.750000
max    400.000000

In [14]:
df_hospedes.columns

Index(['id_hospede', 'nome', 'email', 'telefone', 'cidade_origem', 'estado',
       'data_nascimento', 'genero'],
      dtype='str')

In [15]:
df_quartos.info()

<class 'pandas.DataFrame'>
RangeIndex: 58 entries, 0 to 57
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id_quarto    58 non-null     str
 1   id_hotel     58 non-null     int64
 2   tipo_quarto  58 non-null     str
 3   capacidade   58 non-null     int64
 4   valor_base   54 non-null     float64
 5   andar        58 non-null     int64
 6   vista        58 non-null     str
dtypes: float64(1), int64(3), str(3)
memory usage: 3.3 KB

In [16]:
df_quartos.describe()

        id_hotel  capacidade   valor_base      andar
count  58.000000   58.000000    54.000000  58.000000
mean    3.120690    3.137931   788.888889   6.189655
std     1.655163    1.627055   596.317842   3.506670
min     1.000000   -2.000000   260.000000   1.000000
25%     2.000000    2.000000   400.000000   3.000000
50%     3.000000    3.000000   570.000000   6.000000
75%     4.000000    4.000000  1025.000000   9.000000
max     9.000000    6.000000  2800.000000  15.000000

In [17]:
df_quartos.columns

Index(['id_quarto', 'id_hotel', 'tipo_quarto', 'capacidade', 'valor_base',
       'andar', 'vista'],
      dtype='str')

In [18]:
df_reservas.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_reserva      1000 non-null   int64
 1   id_hospede      1000 non-null   int64
 2   id_quarto       1000 non-null   str
 3   id_hotel        1000 non-null   int64
 4   data_checkin    1000 non-null   str
 5   data_checkout   1000 non-null   str
 6   canal_reserva   995 non-null    str
 7   valor_diaria    997 non-null    float64
 8   status_reserva  1000 non-null   str
 9   data_reserva    1000 non-null   str
dtypes: float64(1), int64(3), str(6)
memory usage: 78.3 KB

In [19]:
df_reservas.describe()

        id_reserva   id_hospede     id_hotel  valor_diaria
count  1000.000000  1000.000000  1000.000000    997.000000
mean    500.500000   197.571000     2.900000   1615.287482
std     288.819436   123.069562     1.426196   1551.606985
min       1.000000     1.000000     1.000000   -274.840000
25%     250.750000    91.000000     2.000000    895.600000
50%     500.500000   192.000000     3.000000   1528.240000
75%     750.250000   296.000000     4.000000   2138.140000
max    1000.000000   975.000000     5.000000  24637.280000

In [20]:
df_reservas.columns

Index(['id_reserva', 'id_hospede', 'id_quarto', 'id_hotel', 'data_checkin',
       'data_checkout', 'canal_reserva', 'valor_diaria', 'status_reserva',
       'data_reserva'],
      dtype='str')